### ISSUE TITLE
[Application] Mr

### ISSUE THREAD

**Issue by PartnershipDude** [dcdao/profiles#39]
### Nickname

Partnership Dude 

### Picture

8592a5b4f92443c7ad202c7f87c0978d

### Role

Ambassador, Researcher, Moderator, Other-Contributor

### Address

0x048C592C8FDcCE21ff6AF18365D37208a9954f95

### Saying

Looking forward to smiling everyday; bother not.

### Contribution

Greetings.
I’m David by name. A Clinical Student Doctor with love for Web3.

Started contributing to Darwinia since December 2021. Majorly doing education, moderation and Video creation.

Was very instrumental during the launch of Columbus continent on Evolution Land; notifying the ecosystem of daily auctions.

Also have worked collaboratively with other ambassadors on joint events.

Of recent, I began reviving Darwinia AMA spaces by creating social audiograms, and that I must say is the least to expect.

And also a few threads 🧵 that are research focused. 

Let’s do more!

### Google Forms(Optional)

- [X] I've filled the form.

**Comment by PartnershipDude** [comment]
My application is pending for a long time.

**Comment by Cindy884** [comment]
Hello Partnershipdude, 
Thks for your application and congratulations you have got the DCDAO Profile.
We hope to see your participation in DCDAO governance in the future and vote for the proposal.

**Comment by PartnershipDude** [comment]
Still can't vote on snapshot. Where do I see my NFT @Cindy884 @furoxr

**Comment by Laki389** [comment]
> Still can't vote on snapshot. Where do I see my NFT @Cindy884 @furoxr

As I know these DCDAO governance NFTs are minted in bulk once a month. Also DCDAO governance is being migrated to Darwinia chain. You can't vote on Snapshot because those proposals are on Ethereum and I don't think your NFT is even minted yet, and it's not logical for DCDAO to pay ETH fees when it's already clear that governance is being transferred to the Darwinia chain. So I think your NFT will be issued on Darwinia chain (or already issued) and you will be able to vote on new proposals that will be on Darwinia chain.

**Comment by furoxr** [comment]
Yes, Laki is right, I will trigger the MINT transaction today, and after the NFT minted on the Darwinia you will be able to vote on new proposals~

**Comment by furoxr** [comment]
You could import this NFT in your Metamask wallet with
- Contract address: 0x02bE69cF9172a3DcbB334DB9DE41E899F4A8481D
- Token id: 10

**Comment by PartnershipDude** [comment]
Doing this now, Nada. Believe it will be a success.
