### ISSUE TITLE
[Application] DrCAO application 

### ISSUE THREAD

**Issue by caorenzhi** [dcdao/profiles#47]
### Nickname

DrCAO

### Picture

206738c2e50e499d995dd8f4fd8eb6f8

### Role

Developer, Ambassador

### Address

0xbd209B6A11bBA7CaCd22d285f01f68a50c28c255

### Saying

DCDAO, the future of DAO

### Contribution

Made videos for Darwinia before
Maybe build a discord bot and tg bot for Darwinia
Answer questions
Provide ideas

### Google Forms(Optional)

- [ ] I've filled the form.

**Comment by casinoyoda** [comment]
Hello~ Could you kindly update your wallet address to the H160 format? We will be sending the NFT to this H160 address on the Darwinia network.

Since the migration to Darwinia 2.0, please note that the only valid address format on the Darwinia Network is the H160 address, which is compatible with Ethereum wallet addresses.

For further information and historical context, you can refer to these documents: 
1. [Darwinia 2.0 Will Unify Address Format And Precision](https://medium.com/darwinianetwork/darwinia-2-0-will-unify-address-format-and-precision-309ad9a20bf2).
2. [Darwinia 2.0 Blockchain Data Migration](https://medium.com/darwinianetwork/darwinia-2-0-blockchain-data-migration-c1186338c743)

**Comment by Cindy884** [comment]
0xbd209B6A11bBA7CaCd22d285f01f68a50c28c255
here is the Dr.Cao‘s wallet address.
